# -*- coding: utf-8 -*-
"""Tutorial_class_practice .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9m9DQx99Sowfa6Kcw6UIKm-KfunkETY
"""

print("Name:Arnob ID:2530551 Section:2")

print("Name:Arnob")
print("ID:2530551")
print("Section:2")

print("12345678910")

print('1 2 3 4 5 6 7 8 9 10')

input("Student Name:")
input("Student ID:")
input("Section:")

name = "Arnob"

print("My name is", name)
print(f"My name is {name}")

print(type("Name:Arnob"))
print(type(2530551))