# -*- coding: utf-8 -*-
"""Python practice class 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhNqt3xxcBn1meJ77DYq_bSstv3nlwLf
"""

print("Arnob")

print("My name is Arnob")

print('hduajh hudahfd safbsbfasbasf')

print("dah dhafbjsajfsajhfashfasjgajskgjhks")
print("dahfhsajnfsajgfjsajgasbjgjsagjg")

a = 5
abc = 33
a_b = 55

print(a)
print(abc)
print(a_b)

print(a, abc, a_b)

print("a:", a, "abc:" ,abc)

#problem
print("My name:", "Arnob")
print("Student id:","2530551" )

name = "Arnob"
id = 2530551

print("Name:", name)
print("Student id:",id)

id = 2530551
course = "CSE100"
CGPA = 4.00

print("My ID:", id, "\nCourse name:", course, "\nStudent CGPA:", CGPA)

a = 8428412
b = "egwhhhf"
c = 2.56
d = True

print(type(a))
print(type(b))
print(type(c))
print(type(d))

